// Generated by CoffeeScript 1.9.2
var $, ImageLoader, IndexSlider;

$ = window.jQuery;

ImageLoader = (function() {
  function ImageLoader() {}

  ImageLoader.prototype.load = function(url, callback) {
    var image;
    this.loadCallback = callback;
    image = new Image();
    image.src = url;
    return image.onload = (function(_this) {
      return function() {
        if (_this.loadCallback && (_this.loadCallback === callback)) {
          _this.loadCallback();
          return _this.loadCallback = null;
        }
      };
    })(this);
  };

  ImageLoader.prototype.removeCallbacks = function() {
    return this.loadCallback = null;
  };

  return ImageLoader;

})();

IndexSlider = (function() {
  function IndexSlider() {}

  IndexSlider.prototype.init = function() {
    this.switchInterval = 4000;
    this.imageLoader = new ImageLoader();
    this.slideNum = $('.index__slider--data-item').length;
    this.initDOM();
    this.resize();
    this.addListeners();
    return this.changeToSlide(0);
  };

  IndexSlider.prototype.initDOM = function() {
    var i, j, ref;
    $('<div class="index__slider"> <div class="index__slider__spinner"> <div class="sk-cube-grid"> <div class="sk-cube sk-cube1"></div> <div class="sk-cube sk-cube2"></div> <div class="sk-cube sk-cube3"></div> <div class="sk-cube sk-cube4"></div> <div class="sk-cube sk-cube5"></div> <div class="sk-cube sk-cube6"></div> <div class="sk-cube sk-cube7"></div> <div class="sk-cube sk-cube8"></div> <div class="sk-cube sk-cube9"></div> </div> </div> <div class="index__slider__stage"> <div class="index__slider__image-area"></div> <div class="index__slider__desc"> <div class="content-container"> <div class="index__slider__content-area"></div> <div class="index__slider__control-area"></div> </div> </div> </div> <div class="index__slider__move index__slider__role-prev"><i class="icon-chevron_left"></i></div> <div class="index__slider__move index__slider__role-next"><i class="icon-chevron_right"></i></div> </div>').appendTo('.fp__slider');
    $('<span class="index__slider__control-item index__slider__role-prev"><i class="icon-chevron-left"></i></span>').appendTo('.index__slider__control-area');
    for (i = j = 0, ref = this.slideNum; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      $('<span class="index__slider__control-item index__slider__role-switch"><i class="icon-circle"></i></span>').appendTo('.index__slider__control-area');
    }
    return $('<span class="index__slider__control-item index__slider__role-next"><i class="icon-chevron-right"></i></span>').appendTo('.index__slider__control-area');
  };

  IndexSlider.prototype.addListeners = function() {
    var self;
    self = this;
    $('.index__slider__role-switch').click(function() {
      var slideIndex;
      slideIndex = $(this).index() - 1;
      return self.changeToSlide(slideIndex);
    });
    $('.index__slider__role-prev').click(function() {
      return self.changeToPrev();
    });
    $('.index__slider__role-next').click(function() {
      return self.changeToNext();
    });
    return $(window).resize(function() {
      return self.resize();
    });
  };

  IndexSlider.prototype.resize = function() {
    return $('.index__slider').css('height', window.innerHeight + 'px');
  };

  IndexSlider.prototype.showSpinner = function() {
    return $('.index__slider__spinner').addClass('index__slider__spinner--show');
  };

  IndexSlider.prototype.hideSpinner = function() {
    return $('.index__slider__spinner').removeClass('index__slider__spinner--show');
  };

  IndexSlider.prototype.changeToPrev = function() {
    this.currentSlide--;
    if (this.currentSlide < 0) {
      this.currentSlide = this.slideNum - 1;
    }
    return this.changeToSlide(this.currentSlide);
  };

  IndexSlider.prototype.changeToNext = function() {
    this.currentSlide++;
    if (this.currentSlide >= this.slideNum) {
      this.currentSlide = 0;
    }
    return this.changeToSlide(this.currentSlide);
  };

  IndexSlider.prototype.changeToSlide = function(idx) {
    var $newContent, $newImage, $slide, imgUrl, lastItem;
    this.cancelSwitch();
    this.imageLoader.removeCallbacks();
    this.currentSlide = idx;
    $('.index__slider__role-switch').removeClass('index__slider__circle--activated');
    $('.index__slider__role-switch').eq(idx).addClass('index__slider__circle--activated');
    lastItem = $('.index__slider__item');
    lastItem.removeClass('index__slider__item--shown');
    setTimeout(function() {
      return lastItem.remove();
    }, 500);
    $slide = $('.index__slider--data-item').eq(idx);
    imgUrl = $slide.attr('data-src');
    this.showSpinner();
    this.imageLoader.load(imgUrl, (function(_this) {
      return function() {
        var nextImageUrl;
        _this.hideSpinner();
        _this.prepareSwitchToNext();
        nextImageUrl = $('.index__slider--data-item').eq((idx + 1) % _this.slideNum).attr('data-src');
        return _this.imageLoader.load(nextImageUrl);
      };
    })(this));
    $newImage = $('<div>').addClass('index__slider__item index__slider__image').css('background-image', 'url("' + imgUrl + '")').appendTo('.index__slider__image-area');
    $newContent = $('<div>').addClass('index__slider__item index__slider__text').html($slide.html()).appendTo('.index__slider__content-area');
    $('.index__slider').width();
    $newImage.addClass('index__slider__item--shown');
    return $newContent.addClass('index__slider__item--shown');
  };

  IndexSlider.prototype.cancelSwitch = function() {
    if (this.switcher) {
      clearTimeout(this.switcher);
    }
    return this.switcher = null;
  };

  IndexSlider.prototype.prepareSwitchToNext = function() {
    return this.switcher = setTimeout((function(_this) {
      return function() {
        _this.changeToNext();
        return _this.switcher = null;
      };
    })(this), this.switchInterval);
  };

  return IndexSlider;

})();

$(document).ready(function() {
  var slider;
  slider = new IndexSlider();
  return slider.init();
});
